---
abstract: 'Catalyst based application'
author:
  - 'Stefan Seifert'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CiderWebmail
no_index:
  directory:
    - inc
    - t
requires:
  Cache::FastMmap: 0
  Catalyst::Action::RenderView: 0
  Catalyst::Authentication::Credential::HTTP: 0
  Catalyst::Model::DBIC::Schema: 0
  Catalyst::Plugin::Authentication: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Session::Store::FastMmap: 0
  Catalyst::Plugin::StackTrace: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Plugin::Unicode: 0
  Catalyst::Runtime: 5.7012
  Catalyst::View::Petal: 0
  Clone: 0
  Data::ICal: 0
  DateTime: 0
  DateTime::Format::ISO8601: 0
  DateTime::Format::Mail: 0
  Email::Address: 0
  Email::Simple: 0
  HTML::Scrubber: 0
  HTML::Tidy: 0
  IO::Socket::SSL: 0
  List::MoreUtils: 0
  Locale::Maketext::Gettext: 0
  MIME::Lite: 0
  MIME::Parser: 0
  MIME::Tools: 0
  MIME::WordDecoder: 0
  MIME::Words: 0
  Mail::IMAPClient: 0
  Petal::Utils: 0
  Regexp::Common::Email::Address: 0
  Text::Flowed: 0
  Text::Iconv: 0
  URI::QueryParam: 0
  YAML: 0
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.00
