abstract: Catalyst based application
author: Stefan Seifert
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: CiderWebmail
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Action::RenderView: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Runtime: 5.7012
  YAML: 0
version: 0.01
