--- 
abstract: Catalyst based application
author: 
  - Stefan Seifert
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: CiderWebmail
no_index: 
  directory: 
    - inc
    - t
requires: 
  Cache::FastMmap: 0
  Catalyst::Action::RenderView: 0
  Catalyst::Authentication::Credential::HTTP: 0
  Catalyst::Plugin::Authentication: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Session::Store::FastMmap: 0
  Catalyst::Plugin::StackTrace: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Plugin::Unicode: 0
  Catalyst::Runtime: 5.7012
  Catalyst::View::Petal: 0
  Clone: 0
  DateTime: 0
  DateTime::Format::Mail: 0
  Email::Simple: 0
  IO::Socket::SSL: 0
  MIME::Lite: 0
  MIME::Parser: 0
  MIME::Tools: 0
  MIME::WordDecoder: 0
  MIME::Words: 0
  Mail::IMAPClient: 0
  Petal::Utils: 0
  Text::Flowed: 0
  Text::Iconv: 0
  YAML: 0
  parent: 0
version: 0.01
